# Generated by Django 5.1.9 on 2025-05-14 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="browser_notifications",
            field=models.BooleanField(default=True, verbose_name="إشعارات المتصفح"),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="إشعارات البريد الإلكتروني"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "مدير النظام"),
                    ("manager", "مدير"),
                    ("employee", "موظف"),
                    ("viewer", "مشاهد"),
                ],
                default="employee",
                max_length=20,
                verbose_name="الدور",
            ),
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("invoice", "فاتورة جديدة"),
                            ("payment", "دفعة جديدة"),
                            ("user", "مستخدم جديد"),
                            ("product", "منتج جديد"),
                            ("contact", "جهة اتصال جديدة"),
                            ("system", "إشعار نظام"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرف الكائن المرتبط"
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="نوع الكائن المرتبط",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="الرابط"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
    ]
