# Generated by Django 5.2.1 on 2025-05-15 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0007_alter_producttransaction_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الموظف")),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="الرقم القومي",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="المسمى الوظيفي",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="القسم"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التعيين"
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الراتب",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("inactive", "غير نشط"),
                            ("on_leave", "في إجازة"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
            ],
            options={
                "verbose_name": "موظف",
                "verbose_name_plural": "الموظفين",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ السلفة"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="تم السداد"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ السداد"
                    ),
                ),
                ("is_posted", models.BooleanField(default=False, verbose_name="مرحل")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "safe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_loans",
                        to="core.safe",
                        verbose_name="الخزنة",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_loan",
                        to="finances.safetransaction",
                        verbose_name="حركة الخزنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سلفة موظف",
                "verbose_name_plural": "سلف الموظفين",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="التاريخ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غائب"),
                            ("excused", "غائب بعذر"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "check_in",
                    models.TimeField(blank=True, null=True, verbose_name="وقت الحضور"),
                ),
                (
                    "check_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="وقت الانصراف"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل الحضور",
                "verbose_name_plural": "سجلات الحضور",
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        verbose_name="الشهر",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="السنة")),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الراتب الأساسي"
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الخصومات",
                    ),
                ),
                (
                    "loans_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="خصم السلف",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="صافي الراتب"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ الصرف"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="تم الصرف"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                ("is_posted", models.BooleanField(default=False, verbose_name="مرحل")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "safe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_salaries",
                        to="core.safe",
                        verbose_name="الخزنة",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_salary",
                        to="finances.safetransaction",
                        verbose_name="حركة الخزنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "راتب",
                "verbose_name_plural": "المرتبات",
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "month", "year")},
            },
        ),
    ]
