# Generated by Django 5.2.1 on 2025-05-17 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_invoice_type",
                    models.CharField(
                        choices=[("cash", "نقدي"), ("credit", "آجل")],
                        default="cash",
                        max_length=10,
                        verbose_name="النوع الافتراضي للفاتورة",
                    ),
                ),
                (
                    "update_purchase_price",
                    models.BooleanField(
                        default=True, verbose_name="تحديث سعر الشراء من آخر فاتورة"
                    ),
                ),
                (
                    "update_sale_price",
                    models.BooleanField(
                        default=False, verbose_name="تحديث سعر البيع من آخر فاتورة"
                    ),
                ),
                (
                    "alert_below_sale_price",
                    models.BooleanField(
                        default=True,
                        verbose_name="التنبيه عند البيع بسعر أقل من سعر البيع",
                    ),
                ),
                (
                    "alert_below_purchase_price",
                    models.BooleanField(
                        default=True,
                        verbose_name="التنبيه عند البيع بسعر أقل من سعر الشراء",
                    ),
                ),
                (
                    "allow_duplicate_items",
                    models.BooleanField(
                        default=False,
                        verbose_name="السماح بتكرار الصنف في بنود الفاتورة",
                    ),
                ),
                (
                    "auto_increase_quantity",
                    models.BooleanField(
                        default=True,
                        verbose_name="زيادة الكمية تلقائياً عند تكرار الصنف",
                    ),
                ),
                (
                    "hide_company_info",
                    models.BooleanField(
                        default=False, verbose_name="إخفاء بيانات الشركة في الفاتورة"
                    ),
                ),
                (
                    "show_previous_balance",
                    models.BooleanField(
                        default=True, verbose_name="إظهار الحساب السابق للعميل"
                    ),
                ),
                (
                    "invoice_header_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="نص رأس الفاتورة"
                    ),
                ),
                (
                    "invoice_footer_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="نص ذيل الفاتورة"
                    ),
                ),
                (
                    "default_customer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"contact_type": "customer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_customer_settings",
                        to="core.contact",
                        verbose_name="العميل الافتراضي لفواتير البيع",
                    ),
                ),
                (
                    "default_safe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_safe_settings",
                        to="core.safe",
                        verbose_name="الخزنة الافتراضية",
                    ),
                ),
                (
                    "default_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_store_settings",
                        to="core.store",
                        verbose_name="المخزن الافتراضي",
                    ),
                ),
                (
                    "default_supplier",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"contact_type": "supplier"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_supplier_settings",
                        to="core.contact",
                        verbose_name="المورد الافتراضي لفواتير الشراء",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات النظام",
                "verbose_name_plural": "إعدادات النظام",
            },
        ),
    ]
