# Generated by Django 5.2.1 on 2025-05-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="duplicate_item_handling",
            field=models.CharField(
                choices=[
                    ("allow_duplicate", "السماح بتكرار الصنف في بنود الفاتورة"),
                    ("increase_quantity", "زيادة الكمية تلقائياً عند تكرار الصنف"),
                ],
                default="increase_quantity",
                max_length=20,
                verbose_name="التعامل مع تكرار الصنف",
            ),
        ),
    ]
