# Generated by Django 5.2.1 on 2025-05-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_old_duplicate_item_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="allow_duplicate_items",
            field=models.BooleanField(
                default=False, verbose_name="السماح بتكرار الصنف في بنود الفاتورة"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="auto_increase_quantity",
            field=models.BooleanField(
                default=True, verbose_name="زيادة الكمية تلقائياً عند تكرار الصنف"
            ),
        ),
    ]
