# Generated by Django 5.2.1 on 2025-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_systemsettings_allow_duplicate_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="show_driver_in_permit_report",
            field=models.BooleanField(
                default=True, verbose_name="إظهار حقل السائق في تقرير الأذونات"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="show_representative_in_permit_report",
            field=models.BooleanField(
                default=True, verbose_name="إظهار حقل المندوب في تقرير الأذونات"
            ),
        ),
    ]
