# Generated by Django 5.2.1 on 2025-05-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0002_alter_contacttransaction_transaction_type_and_more"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="رقم المستند")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المستند"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("collection", "تحصيل"), ("payment", "دفع")],
                        max_length=15,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدي"),
                            ("bank_transfer", "تحويل بنكي"),
                            ("check", "شيك"),
                            ("credit_card", "بطاقة ائتمان"),
                            ("other", "طريقة أخرى"),
                        ],
                        default="cash",
                        max_length=15,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("is_posted", models.BooleanField(default=False, verbose_name="مرحل")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.contact",
                        verbose_name="جهة الاتصال",
                    ),
                ),
                (
                    "contact_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="finances.contacttransaction",
                        verbose_name="حركة الحساب",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="invoices.invoice",
                        verbose_name="الفاتورة المرتبطة",
                    ),
                ),
                (
                    "safe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.safe",
                        verbose_name="الخزنة",
                    ),
                ),
                (
                    "safe_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="finances.safetransaction",
                        verbose_name="حركة الخزنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سند قبض/صرف",
                "verbose_name_plural": "سندات القبض والصرف",
            },
        ),
    ]
