# Generated by Django 5.2.1 on 2025-05-11 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0005_alter_expense_is_posted_alter_income_is_posted_and_more"),
        ("invoices", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-date"],
                "verbose_name": "تحصيل/دفع",
                "verbose_name_plural": "التحصيلات والمدفوعات",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="safe_transaction",
        ),
        migrations.AddField(
            model_name="payment",
            name="created_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_payment",
                to="finances.safetransaction",
                verbose_name="حركة الخزنة المنشأة",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="core.contact",
                verbose_name="العميل/المورد",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="contact_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="finances.contacttransaction",
                verbose_name="حركة حساب العميل/المورد",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="is_posted",
            field=models.BooleanField(default=True, verbose_name="مرحل"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("receipt", "تحصيل من العميل"), ("payment", "دفع للمورد")],
                max_length=10,
                verbose_name="نوع العملية",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="safe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_payments",
                to="core.safe",
                verbose_name="الخزنة",
            ),
        ),
    ]
