# Generated by Django 5.2.1 on 2025-05-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0003_alter_payment_options_remove_payment_payment_method_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="is_posted",
            field=models.BooleanField(default=True, verbose_name="مرحلة"),
        ),
    ]
