# Generated by Django 5.2.1 on 2025-05-15 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_alter_invoice_is_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ الفاتورة"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ المستند"
            ),
        ),
    ]
