# Generated by Django 5.2.1 on 2025-05-09 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatchery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchIncubation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incubation_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التسكين"
                    ),
                ),
                (
                    "incubation_quantity",
                    models.PositiveIntegerField(verbose_name="عدد التسكين"),
                ),
                (
                    "damaged_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="المعدم عند التسكين"
                    ),
                ),
                (
                    "expected_hatch_date",
                    models.DateField(verbose_name="تاريخ الخروج المتوقع"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "batch_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incubations",
                        to="hatchery.batchentry",
                        verbose_name="الدفعة الواردة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسكين دفعة",
                "verbose_name_plural": "تسكين الدفعات",
                "ordering": ["-incubation_date"],
            },
        ),
    ]
