# Generated by Django 5.2.1 on 2025-05-09 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatchery", "0002_batchincubation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchHatching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hatch_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الخروج"
                    ),
                ),
                (
                    "chicks_count",
                    models.PositiveIntegerField(verbose_name="عدد الكتاكيت"),
                ),
                (
                    "culled_count",
                    models.PositiveIntegerField(verbose_name="عدد الفرزة"),
                ),
                ("dead_count", models.PositiveIntegerField(verbose_name="عدد الفاطس")),
                (
                    "fertility_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="نسبة الإخصاب (%)"
                    ),
                ),
                (
                    "hatch_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="نسبة الفقس الحقيقية (%)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "incubation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hatching",
                        to="hatchery.batchincubation",
                        verbose_name="الدفعة المسكنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "خروج دفعة",
                "verbose_name_plural": "خروج الدفعات",
                "ordering": ["-hatch_date"],
            },
        ),
    ]
