# Generated by Django 5.2.1 on 2025-05-10 00:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatchery", "0004_customer_culledsale"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisinfectantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم التصنيف"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف التصنيف"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تصنيف مطهر",
                "verbose_name_plural": "تصنيفات المطهرات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DisinfectantInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المطهر")),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="المورد"
                    ),
                ),
                ("unit", models.CharField(max_length=50, verbose_name="وحدة القياس")),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المخزون الحالي",
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الحد الأدنى للمخزون",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="hatchery.disinfectantcategory",
                        verbose_name="تصنيف المطهر",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخزون مطهر",
                "verbose_name_plural": "مخزون المطهرات",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DisinfectantTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("receive", "استلام"), ("dispense", "صرف")],
                        max_length=10,
                        verbose_name="نوع الحركة",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الحركة"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الكمية"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "disinfectant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="hatchery.disinfectantinventory",
                        verbose_name="المطهر",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة مطهر",
                "verbose_name_plural": "حركات المطهرات",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
