# Generated by Django 5.2.1 on 2025-05-10 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatchery", "0005_disinfectantcategory_disinfectantinventory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التوزيع"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "hatching",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distributions",
                        to="hatchery.batchhatching",
                        verbose_name="دفعة الخروج",
                    ),
                ),
            ],
            options={
                "verbose_name": "توزيع دفعة",
                "verbose_name_plural": "توزيعات الدفعات",
                "ordering": ["-distribution_date"],
            },
        ),
        migrations.CreateModel(
            name="BatchDistributionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chicks_count",
                    models.PositiveIntegerField(verbose_name="عدد الكتاكيت"),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر للوحدة"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المبلغ المدفوع",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_items",
                        to="hatchery.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_items",
                        to="hatchery.batchdistribution",
                        verbose_name="توزيع الدفعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر توزيع",
                "verbose_name_plural": "عناصر التوزيع",
            },
        ),
    ]
