# Generated by Django 5.2.1 on 2025-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatchery", "0006_batchdistribution_batchdistributionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchdistribution",
            name="driver",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="اسم السائق"
            ),
        ),
    ]
