# Generated by Django 5.2.1 on 2025-05-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatchery", "0007_batchdistribution_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchdistribution",
            name="driver",
        ),
        migrations.AddField(
            model_name="batchdistributionitem",
            name="driver",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="اسم السائق"
            ),
        ),
    ]
