# Generated by Django 5.2.1 on 2025-05-26 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatchery", "0008_remove_batchdistribution_driver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchdistribution",
            name="is_merged",
            field=models.BooleanField(default=False, verbose_name="توزيع مدمج"),
        ),
        migrations.AlterField(
            model_name="batchdistribution",
            name="hatching",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distributions",
                to="hatchery.batchhatching",
                verbose_name="دفعة الخروج",
            ),
        ),
        migrations.CreateModel(
            name="MergedBatchDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chicks_count_from_batch",
                    models.PositiveIntegerField(
                        help_text="عدد الكتاكيت المأخوذة من هذه الدفعة للتوزيع المدمج",
                        verbose_name="عدد الكتاكيت من هذه الدفعة",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hatchery.batchdistribution",
                        verbose_name="التوزيع",
                    ),
                ),
                (
                    "hatching",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hatchery.batchhatching",
                        verbose_name="دفعة الخروج",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة في التوزيع المدمج",
                "verbose_name_plural": "الدفعات في التوزيع المدمج",
                "unique_together": {("distribution", "hatching")},
            },
        ),
        migrations.AddField(
            model_name="batchdistribution",
            name="merged_hatchings",
            field=models.ManyToManyField(
                blank=True,
                related_name="merged_distributions",
                through="hatchery.MergedBatchDistribution",
                to="hatchery.batchhatching",
                verbose_name="الدفعات المدمجة",
            ),
        ),
    ]
