# Generated by Django 5.2.1 on 2025-05-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("invoices", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ العملية"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("invoice", "فاتورة"),
                            ("collection", "تحصيل"),
                            ("payment", "دفع"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="الرصيد قبل العملية",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="الرصيد بعد العملية",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.contact",
                        verbose_name="جهة الاتصال",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_transactions",
                        to="invoices.invoice",
                        verbose_name="الفاتورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة حساب",
                "verbose_name_plural": "حركات الحسابات",
            },
        ),
        migrations.CreateModel(
            name="ProductTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ العملية"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="الكمية"
                    ),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=15,
                        verbose_name="الكمية بالوحدة الأساسية",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sale", "بيع"),
                            ("purchase", "شراء"),
                            ("sale_return", "مرتجع بيع"),
                            ("purchase_return", "مرتجع شراء"),
                            ("adjustment", "تسوية مخزون"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=15,
                        verbose_name="الرصيد قبل العملية",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=15,
                        verbose_name="الرصيد بعد العملية",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_transactions",
                        to="invoices.invoice",
                        verbose_name="الفاتورة",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="products.productunit",
                        verbose_name="وحدة المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة منتج",
                "verbose_name_plural": "حركات المنتجات",
            },
        ),
        migrations.CreateModel(
            name="SafeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ العملية"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("invoice", "فاتورة"),
                            ("collection", "تحصيل"),
                            ("payment", "دفع"),
                            ("deposit", "إيداع"),
                            ("withdrawal", "سحب"),
                            ("expense", "مصروف"),
                            ("income", "إيراد"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="الرصيد قبل العملية",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="الرصيد بعد العملية",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safe_transactions",
                        to="core.contact",
                        verbose_name="جهة الاتصال",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safe_transactions",
                        to="invoices.invoice",
                        verbose_name="الفاتورة",
                    ),
                ),
                (
                    "safe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.safe",
                        verbose_name="الخزنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة الخزنة",
                "verbose_name_plural": "حركات الخزنة",
            },
        ),
    ]
