# Generated by Django 5.2.1 on 2025-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("sale_invoice", "فاتورة بيع"),
                    ("purchase_invoice", "فاتورة شراء"),
                    ("sale_return_invoice", "مرتجع بيع"),
                    ("purchase_return_invoice", "مرتجع شراء"),
                    ("collection", "تحصيل"),
                    ("payment", "دفع"),
                ],
                max_length=25,
                verbose_name="نوع العملية",
            ),
        ),
        migrations.AlterField(
            model_name="safetransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("sale_invoice", "فاتورة بيع"),
                    ("purchase_invoice", "فاتورة شراء"),
                    ("sale_return_invoice", "مرتجع بيع"),
                    ("purchase_return_invoice", "مرتجع شراء"),
                    ("collection", "تحصيل"),
                    ("payment", "دفع"),
                    ("deposit", "إيداع"),
                    ("withdrawal", "سحب"),
                    ("expense", "مصروف"),
                    ("income", "إيراد"),
                ],
                max_length=25,
                verbose_name="نوع العملية",
            ),
        ),
    ]
