# Generated by Django 5.2.1 on 2025-05-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0002_alter_contacttransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القسم")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="finances.expensecategory",
                        verbose_name="القسم الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم المصروفات",
                "verbose_name_plural": "أقسام المصروفات",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="رقم المستند")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المستند"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ"
                    ),
                ),
                ("payee", models.CharField(max_length=255, verbose_name="المستفيد")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("is_posted", models.BooleanField(default=False, verbose_name="مرحل")),
                (
                    "safe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="core.safe",
                        verbose_name="الخزنة",
                    ),
                ),
                (
                    "safe_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense",
                        to="finances.safetransaction",
                        verbose_name="حركة الخزنة",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finances.expensecategory",
                        verbose_name="قسم المصروفات",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصروف",
                "verbose_name_plural": "المصروفات",
            },
        ),
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القسم")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="finances.incomecategory",
                        verbose_name="القسم الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم الإيرادات",
                "verbose_name_plural": "أقسام الإيرادات",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="رقم المستند")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المستند"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ"
                    ),
                ),
                ("payer", models.CharField(max_length=255, verbose_name="الدافع")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("is_posted", models.BooleanField(default=False, verbose_name="مرحل")),
                (
                    "safe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to="core.safe",
                        verbose_name="الخزنة",
                    ),
                ),
                (
                    "safe_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income",
                        to="finances.safetransaction",
                        verbose_name="حركة الخزنة",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incomes",
                        to="finances.incomecategory",
                        verbose_name="قسم الإيرادات",
                    ),
                ),
            ],
            options={
                "verbose_name": "إيراد",
                "verbose_name_plural": "الإيرادات",
            },
        ),
        migrations.CreateModel(
            name="SafeDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="رقم المستند")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المستند"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ"
                    ),
                ),
                (
                    "source",
                    models.CharField(max_length=255, verbose_name="مصدر الإيداع"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("is_posted", models.BooleanField(default=False, verbose_name="مرحل")),
                (
                    "safe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="core.safe",
                        verbose_name="الخزنة",
                    ),
                ),
                (
                    "safe_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposit",
                        to="finances.safetransaction",
                        verbose_name="حركة الخزنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إيداع في الخزنة",
                "verbose_name_plural": "الإيداعات في الخزن",
            },
        ),
        migrations.CreateModel(
            name="SafeWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="رقم المستند")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المستند"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ"
                    ),
                ),
                (
                    "destination",
                    models.CharField(max_length=255, verbose_name="جهة السحب"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("is_posted", models.BooleanField(default=False, verbose_name="مرحل")),
                (
                    "safe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="core.safe",
                        verbose_name="الخزنة",
                    ),
                ),
                (
                    "safe_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal",
                        to="finances.safetransaction",
                        verbose_name="حركة الخزنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سحب من الخزنة",
                "verbose_name_plural": "السحوبات من الخزن",
            },
        ),
    ]
