# Generated by Django 5.2.1 on 2025-05-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_expensecategory_expense_incomecategory_income_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="safe_transaction",
        ),
        migrations.RemoveField(
            model_name="income",
            name="safe_transaction",
        ),
        migrations.RemoveField(
            model_name="safedeposit",
            name="safe_transaction",
        ),
        migrations.RemoveField(
            model_name="safewithdrawal",
            name="safe_transaction",
        ),
        migrations.AddField(
            model_name="expense",
            name="created_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_expense",
                to="finances.safetransaction",
                verbose_name="حركة الخزنة المنشأة",
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="created_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_income",
                to="finances.safetransaction",
                verbose_name="حركة الخزنة المنشأة",
            ),
        ),
        migrations.AddField(
            model_name="safedeposit",
            name="created_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_deposit",
                to="finances.safetransaction",
                verbose_name="حركة الخزنة المنشأة",
            ),
        ),
        migrations.AddField(
            model_name="safewithdrawal",
            name="created_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_withdrawal",
                to="finances.safetransaction",
                verbose_name="حركة الخزنة المنشأة",
            ),
        ),
    ]
