# Generated by Django 5.2.1 on 2025-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_remove_expense_safe_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="is_posted",
            field=models.BooleanField(default=True, verbose_name="مرحل"),
        ),
        migrations.AlterField(
            model_name="income",
            name="is_posted",
            field=models.BooleanField(default=True, verbose_name="مرحل"),
        ),
        migrations.AlterField(
            model_name="safedeposit",
            name="is_posted",
            field=models.BooleanField(default=True, verbose_name="مرحل"),
        ),
        migrations.AlterField(
            model_name="safewithdrawal",
            name="is_posted",
            field=models.BooleanField(default=True, verbose_name="مرحل"),
        ),
    ]
