# Generated by Django 5.2.1 on 2025-05-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0005_alter_expense_is_posted_alter_income_is_posted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacttransaction",
            options={
                "ordering": ["date"],
                "verbose_name": "حركة حساب",
                "verbose_name_plural": "حركات الحسابات",
            },
        ),
        migrations.AlterModelOptions(
            name="producttransaction",
            options={
                "ordering": ["date"],
                "verbose_name": "حركة منتج",
                "verbose_name_plural": "حركات المنتجات",
            },
        ),
        migrations.AlterModelOptions(
            name="safetransaction",
            options={
                "ordering": ["date"],
                "verbose_name": "حركة الخزنة",
                "verbose_name_plural": "حركات الخزنة",
            },
        ),
        migrations.AddField(
            model_name="producttransaction",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_transactions",
                to="core.store",
                verbose_name="المخزن",
            ),
            preserve_default=False,
        ),
    ]
