# Generated by Django 5.2.1 on 2025-05-15 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0006_alter_contacttransaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttransaction",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_transactions",
                to="core.store",
                verbose_name="المخزن",
            ),
        ),
    ]
