# Generated by Django 5.2.1 on 2025-05-15 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0007_alter_producttransaction_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ المستند"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ المستند"
            ),
        ),
        migrations.AlterField(
            model_name="safedeposit",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ المستند"
            ),
        ),
        migrations.AlterField(
            model_name="safewithdrawal",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ المستند"
            ),
        ),
    ]
