# Generated by Django 5.2.1 on 2025-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0008_alter_expense_date_alter_income_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم المستند"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم المستند"
            ),
        ),
        migrations.AlterField(
            model_name="safedeposit",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم المستند"
            ),
        ),
        migrations.AlterField(
            model_name="safewithdrawal",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم المستند"
            ),
        ),
    ]
