# Generated by Django 5.2.1 on 2025-05-15 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0009_alter_expense_number_alter_income_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safetransaction",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ العملية"
            ),
        ),
    ]
