# Generated by Django 5.2.1 on 2025-05-15 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0010_alter_safetransaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacttransaction",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ العملية"
            ),
        ),
        migrations.AlterField(
            model_name="producttransaction",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ العملية"
            ),
        ),
    ]
