# Generated by Django 5.2.1 on 2025-05-16 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0011_alter_contacttransaction_date_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم المستند"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ المستند"
                    ),
                ),
                ("recipient", models.CharField(max_length=255, verbose_name="المستلم")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("is_posted", models.BooleanField(default=True, verbose_name="مرحل")),
                (
                    "created_transactions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="created_by_issue",
                        to="finances.producttransaction",
                        verbose_name="حركات المنتجات المنشأة",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_issues",
                        to="core.driver",
                        verbose_name="السائق",
                    ),
                ),
                (
                    "representative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_issues",
                        to="core.representative",
                        verbose_name="المندوب",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="core.store",
                        verbose_name="المخزن",
                    ),
                ),
            ],
            options={
                "verbose_name": "صرف من المخزن",
                "verbose_name_plural": "عمليات الصرف من المخازن",
            },
        ),
        migrations.CreateModel(
            name="StoreIssueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="الكمية"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finances.storeissue",
                        verbose_name="مستند الصرف",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_items",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_items",
                        to="products.productunit",
                        verbose_name="وحدة المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند صرف",
                "verbose_name_plural": "بنود الصرف",
            },
        ),
        migrations.CreateModel(
            name="StoreReceive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم المستند"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ المستند"
                    ),
                ),
                ("sender", models.CharField(max_length=255, verbose_name="المرسل")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("is_posted", models.BooleanField(default=True, verbose_name="مرحل")),
                (
                    "created_transactions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="created_by_receive",
                        to="finances.producttransaction",
                        verbose_name="حركات المنتجات المنشأة",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_receives",
                        to="core.driver",
                        verbose_name="السائق",
                    ),
                ),
                (
                    "representative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_receives",
                        to="core.representative",
                        verbose_name="المندوب",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receives",
                        to="core.store",
                        verbose_name="المخزن",
                    ),
                ),
            ],
            options={
                "verbose_name": "استلام في المخزن",
                "verbose_name_plural": "عمليات الاستلام في المخازن",
            },
        ),
        migrations.CreateModel(
            name="StoreReceiveItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="الكمية"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive_items",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive_items",
                        to="products.productunit",
                        verbose_name="وحدة المنتج",
                    ),
                ),
                (
                    "receive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finances.storereceive",
                        verbose_name="مستند الاستلام",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند استلام",
                "verbose_name_plural": "بنود الاستلام",
            },
        ),
    ]
