# Generated by Django 5.2.1 on 2025-05-16 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0012_storeissue_storeissueitem_storereceive_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storeissue",
            options={
                "verbose_name": "صرف من المخزن (قديم)",
                "verbose_name_plural": "عمليات الصرف من المخازن (قديم)",
            },
        ),
        migrations.AlterModelOptions(
            name="storeissueitem",
            options={
                "verbose_name": "بند صرف (قديم)",
                "verbose_name_plural": "بنود الصرف (قديم)",
            },
        ),
        migrations.AlterModelOptions(
            name="storereceive",
            options={
                "verbose_name": "استلام في المخزن (قديم)",
                "verbose_name_plural": "عمليات الاستلام في المخازن (قديم)",
            },
        ),
        migrations.AlterModelOptions(
            name="storereceiveitem",
            options={
                "verbose_name": "بند استلام (قديم)",
                "verbose_name_plural": "بنود الاستلام (قديم)",
            },
        ),
        migrations.CreateModel(
            name="StorePermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permit_type",
                    models.CharField(
                        choices=[("issue", "إذن صرف"), ("receive", "إذن استلام")],
                        max_length=10,
                        verbose_name="نوع الإذن",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم المستند"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ المستند"
                    ),
                ),
                (
                    "person_name",
                    models.CharField(
                        help_text="المستلم في حالة الصرف أو المرسل في حالة الاستلام",
                        max_length=255,
                        verbose_name="اسم الشخص",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                ("is_posted", models.BooleanField(default=True, verbose_name="مرحل")),
                (
                    "created_transactions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="created_by_permit",
                        to="finances.producttransaction",
                        verbose_name="حركات المنتجات المنشأة",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_permits",
                        to="core.driver",
                        verbose_name="السائق",
                    ),
                ),
                (
                    "representative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_permits",
                        to="core.representative",
                        verbose_name="المندوب",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_permits",
                        to="core.store",
                        verbose_name="المخزن",
                    ),
                ),
            ],
            options={
                "verbose_name": "إذن مخزني",
                "verbose_name_plural": "أذونات مخزنية",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StorePermitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="الكمية"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "permit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finances.storepermit",
                        verbose_name="الإذن",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permit_items",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permit_items",
                        to="products.productunit",
                        verbose_name="وحدة المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند إذن مخزني",
                "verbose_name_plural": "بنود أذونات مخزنية",
            },
        ),
    ]
