# Generated by Django 5.2.1 on 2025-05-16 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finances", "0013_alter_storeissue_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storepermit",
            options={
                "ordering": ["-date"],
                "verbose_name": "إذن مخزني",
                "verbose_name_plural": "أذونات المخزن",
            },
        ),
        migrations.AlterModelOptions(
            name="storepermititem",
            options={
                "verbose_name": "بند إذن مخزني",
                "verbose_name_plural": "بنود أذونات المخزن",
            },
        ),
        migrations.RemoveField(
            model_name="storepermit",
            name="created_transactions",
        ),
        migrations.AddField(
            model_name="storepermititem",
            name="created_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_permit_item",
                to="finances.producttransaction",
                verbose_name="حركة المنتج المنشأة",
            ),
        ),
        migrations.AlterField(
            model_name="storepermit",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ الإذن"
            ),
        ),
        migrations.AlterField(
            model_name="storepermit",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permits",
                to="core.driver",
                verbose_name="السائق",
            ),
        ),
        migrations.AlterField(
            model_name="storepermit",
            name="is_posted",
            field=models.BooleanField(default=False, verbose_name="مرحل"),
        ),
        migrations.AlterField(
            model_name="storepermit",
            name="number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="رقم الإذن"
            ),
        ),
        migrations.AlterField(
            model_name="storepermit",
            name="representative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permits",
                to="core.representative",
                verbose_name="المندوب",
            ),
        ),
        migrations.AlterField(
            model_name="storepermit",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permits",
                to="core.store",
                verbose_name="المخزن",
            ),
        ),
    ]
