# Generated by Django 5.2.1 on 2025-05-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الوحدة")),
                ("symbol", models.CharField(max_length=10, verbose_name="الرمز")),
            ],
            options={
                "verbose_name": "وحدة",
                "verbose_name_plural": "وحدات القياس",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم القسم")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="القسم الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المنتج")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="كود المنتج"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="الباركود"
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="الرصيد الافتتاحي",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="صورة المنتج",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "default_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_products",
                        to="core.store",
                        verbose_name="المخزن الافتراضي",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج",
                "verbose_name_plural": "المنتجات",
            },
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=10,
                        verbose_name="معامل التحويل",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="سعر الشراء",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="سعر البيع",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="باركود الوحدة",
                    ),
                ),
                (
                    "is_default_purchase",
                    models.BooleanField(
                        default=False, verbose_name="وحدة الشراء الافتراضية"
                    ),
                ),
                (
                    "is_default_sale",
                    models.BooleanField(
                        default=False, verbose_name="وحدة البيع الافتراضية"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_units",
                        to="products.unit",
                        verbose_name="الوحدة",
                    ),
                ),
            ],
            options={
                "verbose_name": "وحدة المنتج",
                "verbose_name_plural": "وحدات المنتجات",
                "unique_together": {("product", "unit")},
            },
        ),
    ]
